<?php
$jobs = [
    [
      'title' => 'HVAC Technician',
      'company' => 'FrostLine Air Systems',
      'location' => 'Taguig, Philippines',
      'salary' => '₱21,000.00 / month',
      'type' => 'Full time',
      'posted' => '4 days ago',
      'deadline' => 'Apply before 20 Apr',
      'level' => 'Mid-Senior Level',
      'logo' => 'rmt.jpg'
    ],
    [
      'title' => 'Aircon Technician',
      'company' => 'CoolEdge Services Inc.',
      'location' => 'Cebu City, Philippines',
      'salary' => '₱19,500.00 / month',
      'type' => 'Full time',
      'posted' => '6 days ago',
      'deadline' => 'Apply before 22 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'ac1.jpg'
    ],
    [
      'title' => 'AC & Refrigeration Specialist',
      'company' => 'BlueAir Technologies',
      'location' => 'Makati, Philippines',
      'salary' => '₱23,000.00 / month',
      'type' => 'Contract',
      'posted' => '3 days ago',
      'deadline' => 'Apply before 24 Apr',
      'level' => 'Mid-Senior Level',
      'logo' => 'ac4.jpg'
    ],
    [
      'title' => 'HVAC Installer',
      'company' => 'AirNova Climate Solutions',
      'location' => 'Quezon City, Philippines',
      'salary' => '₱20,500.00 / month',
      'type' => 'Full time',
      'posted' => '2 days ago',
      'deadline' => 'Apply before 27 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'ac5.jpg'
    ],
    [
      'title' => 'Cooling Systems Technician',
      'company' => 'ThermoLogic Engineering Co.',
      'location' => 'Pasay, Philippines',
      'salary' => '₱18,800.00 / month',
      'type' => 'Full time',
      'posted' => '7 days ago',
      'deadline' => 'Apply before 23 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'ac6.jpg'
    ],
    [
      'title' => 'AC Maintenance Technician',
      'company' => 'PolarZone Facilities',
      'location' => 'Davao City, Philippines',
      'salary' => '₱19,000.00 / month',
      'type' => 'Full time',
      'posted' => '5 days ago',
      'deadline' => 'Apply before 25 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'ac7.jpg'
    ],
    [
      'title' => 'HVAC Service Technician',
      'company' => 'EcoCool Air Services',
      'location' => 'Caloocan, Philippines',
      'salary' => '₱22,000.00 / month',
      'type' => 'Full time',
      'posted' => '1 day ago',
      'deadline' => 'Apply before 28 Apr',
      'level' => 'Mid-Senior Level',
      'logo' => 'ac8.jpg'
    ],
    [
      'title' => 'Air Conditioning Mechanic',
      'company' => 'BreezeTech Solutions',
      'location' => 'San Juan, Philippines',
      'salary' => '₱18,200.00 / month',
      'type' => 'Full time',
      'posted' => '6 days ago',
      'deadline' => 'Apply before 21 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'ac9.jpg'
    ],
    [
      'title' => 'Senior AC Technician',
      'company' => 'ArcticFix Corporation',
      'location' => 'Las Piñas, Philippines',
      'salary' => '₱24,500.00 / month',
      'type' => 'Full time',
      'posted' => '2 days ago',
      'deadline' => 'Apply before 29 Apr',
      'level' => 'Mid-Senior Level',
      'logo' => 'ac10.jpg'
    ],
    [
      'title' => 'Aircon Repair Technician',
      'company' => 'FreshFlow Services',
      'location' => 'Antipolo, Philippines',
      'salary' => '₱17,900.00 / month',
      'type' => 'Part time',
      'posted' => '4 days ago',
      'deadline' => 'Apply before 26 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'ac11.jpg'
    ],
    [
      'title' => 'HVAC Field Technician',
      'company' => 'ColdWave Industrial',
      'location' => 'Valenzuela, Philippines',
      'salary' => '₱20,000.00 / month',
      'type' => 'Full time',
      'posted' => '3 days ago',
      'deadline' => 'Apply before 24 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'ac12.jpg'
    ],
    [
      'title' => 'Air Conditioning Support Tech',
      'company' => 'SmartChill Philippines',
      'location' => 'Marikina, Philippines',
      'salary' => '₱18,500.00 / month',
      'type' => 'Full time',
      'posted' => '6 days ago',
      'deadline' => 'Apply before 25 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'ac13.jpg'
    ],
    [
      'title' => 'Junior HVAC Mechanic',
      'company' => 'ClimaPro Solutions',
      'location' => 'Mandaluyong, Philippines',
      'salary' => '₱19,800.00 / month',
      'type' => 'Full time',
      'posted' => '2 days ago',
      'deadline' => 'Apply before 30 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'ac14.jpg'
    ],
    [
      'title' => 'Chiller Plant Operator',
      'company' => 'FrostGuard Industries',
      'location' => 'Baguio, Philippines',
      'salary' => '₱21,000.00 / month',
      'type' => 'Full time',
      'posted' => '2 days ago',
      'deadline' => 'Apply before 29 Apr',
      'level' => 'Mid-Senior Level',
      'logo' => 'chiller-plant-operator-logo.jpg'
  ],
  [
      'title' => 'Ducting Technician',
      'company' => 'AirDuct Engineering Services',
      'location' => 'Bacoor, Philippines',
      'salary' => '₱19,500.00 / month',
      'type' => 'Full time',
      'posted' => '1 day ago',
      'deadline' => 'Apply before 26 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'ducting-technician-logo.jpg'
  ],
  [
      'title' => 'Ventilation Technician',
      'company' => 'FlowAir Solutions',
      'location' => 'Manila, Philippines',
      'salary' => '₱23,000.00 / month',
      'type' => 'Contract',
      'posted' => '5 days ago',
      'deadline' => 'Apply before 28 Apr',
      'level' => 'Mid-Senior Level',
      'logo' => 'ventilation-technician-logo.jpg'
  ],
  [
      'title' => 'Commercial AC Supervisor',
      'company' => 'MaxCool Engineering',
      'location' => 'Pasig, Philippines',
      'salary' => '₱25,000.00 / month',
      'type' => 'Full time',
      'posted' => '3 days ago',
      'deadline' => 'Apply before 30 Apr',
      'level' => 'Senior Level',
      'logo' => 'commercial-ac-supervisor-logo.jpg'
  ],
  [
      'title' => 'Split-Type AC Technician',
      'company' => 'ChillWise Services',
      'location' => 'Navotas, Philippines',
      'salary' => '₱22,000.00 / month',
      'type' => 'Full time',
      'posted' => '4 days ago',
      'deadline' => 'Apply before 27 Apr',
      'level' => 'Mid-Senior Level',
      'logo' => 'split-type-ac-technician-logo.jpg'
  ],
  [
      'title' => 'AC Systems Diagnostic Expert',
      'company' => 'ClimaCheck PH',
      'location' => 'Manila, Philippines',
      'salary' => '₱28,000.00 / month',
      'type' => 'Full time',
      'posted' => '6 days ago',
      'deadline' => 'Apply before 26 Apr',
      'level' => 'Senior Level',
      'logo' => 'ac-systems-diagnostic-expert-logo.jpg'
  ],
  [
      'title' => 'Air Cooling Systems Assistant',
      'company' => 'CoolTemp Facilities',
      'location' => 'Santa Rosa, Philippines',
      'salary' => '₱18,000.00 / month',
      'type' => 'Part time',
      'posted' => '3 days ago',
      'deadline' => 'Apply before 25 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'air-cooling-systems-assistant-logo.jpg'
  ],
  [
      'title' => 'Central AC Technician',
      'company' => 'PrimeAir Engineering',
      'location' => 'Parañaque, Philippines',
      'salary' => '₱24,000.00 / month',
      'type' => 'Full time',
      'posted' => '1 day ago',
      'deadline' => 'Apply before 29 Apr',
      'level' => 'Mid-Senior Level',
      'logo' => 'central-ac-technician-logo.jpg'
  ],
  [
      'title' => 'Air Conditioning Quality Inspector',
      'company' => 'HVACCheck PH Corp.',
      'location' => 'Cavite, Philippines',
      'salary' => '₱21,500.00 / month',
      'type' => 'Contract',
      'posted' => '5 days ago',
      'deadline' => 'Apply before 28 Apr',
      'level' => 'Mid-Senior Level',
      'logo' => 'air-conditioning-quality-inspector-logo.jpg'
  ],
  [
      'title' => 'Mobile HVAC Troubleshooter',
      'company' => 'AirFleet Solutions',
      'location' => 'Tarlac City, Philippines',
      'salary' => '₱20,500.00 / month',
      'type' => 'Full time',
      'posted' => '2 days ago',
      'deadline' => 'Apply before 27 Apr',
      'level' => 'Entry Level / Junior, Apprentice',
      'logo' => 'mobile-hvac-troubleshooter-logo.jpg'
  ],
  [
    'title' => 'Software Engineer',
    'company' => 'TechSolutions Inc.',
    'location' => 'Manila, Philippines',
    'salary' => '₱40,000.00 / month',
    'type' => 'Full time',
    'posted' => '2 days ago',
    'deadline' => 'Apply before 29 Apr',
    'level' => 'Mid-Senior Level',
    'category' => 'Featured Jobs',
    'logo' => 'software-engineer-logo.jpg'
],
[
    'title' => 'Mechanical Engineer',
    'company' => 'Innovative Designs Corp.',
    'location' => 'Cebu City, Philippines',
    'salary' => '₱35,000.00 / month',
    'type' => 'Full time',
    'posted' => '1 day ago',
    'deadline' => 'Apply before 30 Apr',
    'level' => 'Senior Level',
    'category' => 'New Jobs',
    'logo' => 'mechanical-engineer-logo.jpg'
],
[
    'title' => 'Registered Nurse',
    'company' => 'HealthCare Pro',
    'location' => 'Davao City, Philippines',
    'salary' => '₱18,000.00 / month',
    'type' => 'Full time',
    'posted' => '3 days ago',
    'deadline' => 'Apply before 25 Apr',
    'level' => 'Entry Level / Junior',
    'category' => 'Fresh Grads',
    'logo' => 'registered-nurse-logo.jpg'
],
[
    'title' => 'Civil Engineer',
    'company' => 'Skyline Builders',
    'location' => 'Taguig, Philippines',
    'salary' => '₱50,000.00 / month',
    'type' => 'Full time',
    'posted' => '5 days ago',
    'deadline' => 'Apply before 28 Apr',
    'level' => 'Mid-Senior Level',
    'category' => 'All Jobs',
    'logo' => 'civil-engineer-logo.jpg'
],
[
    'title' => 'UI/UX Designer',
    'company' => 'Designify Solutions',
    'location' => 'Remote',
    'salary' => '₱30,000.00 / month',
    'type' => 'Remote',
    'posted' => '4 days ago',
    'deadline' => 'Apply before 27 Apr',
    'level' => 'Mid-Senior Level',
    'category' => 'Remote Jobs',
    'logo' => 'ui-ux-designer-logo.jpg'
],
[
    'title' => 'Project Manager',
    'company' => 'MegaTech Enterprises',
    'location' => 'Makati, Philippines',
    'salary' => '₱60,000.00 / month',
    'type' => 'Full time',
    'posted' => '6 days ago',
    'deadline' => 'Apply before 29 Apr',
    'level' => 'Senior Level',
    'category' => 'Hybrid',
    'logo' => 'project-manager-logo.jpg'
],
[
    'title' => 'Content Writer',
    'company' => 'WriteRight Agency',
    'location' => 'Remote',
    'salary' => '₱15,000.00 / month',
    'type' => 'Remote',
    'posted' => '7 days ago',
    'deadline' => 'Apply before 30 Apr',
    'level' => 'Entry Level / Junior',
    'category' => 'Remote Jobs',
    'logo' => 'content-writer-logo.jpg'
],
[
    'title' => 'Data Scientist',
    'company' => 'TechNova Analytics',
    'location' => 'Makati, Philippines',
    'salary' => '₱45,000.00 / month',
    'type' => 'Full time',
    'posted' => '1 day ago',
    'deadline' => 'Apply before 25 Apr',
    'level' => 'Mid-Senior Level',
    'category' => 'Featured Jobs',
    'logo' => 'data-scientist-logo.jpg'
],
[
    'title' => 'Electrical Engineer',
    'company' => 'VoltWorks Enterprises',
    'location' => 'Pasig, Philippines',
    'salary' => '₱40,000.00 / month',
    'type' => 'Full time',
    'posted' => '2 days ago',
    'deadline' => 'Apply before 28 Apr',
    'level' => 'Mid-Senior Level',
    'category' => 'All Jobs',
    'logo' => 'electrical-engineer-logo.jpg'
],
[
    'title' => 'Operations Manager',
    'company' => 'Rapid Growth Corp.',
    'location' => 'Quezon City, Philippines',
    'salary' => '₱55,000.00 / month',
    'type' => 'Full time',
    'posted' => '4 days ago',
    'deadline' => 'Apply before 26 Apr',
    'level' => 'Senior Level',
    'category' => 'Hybrid',
    'logo' => 'operations-manager-logo.jpg'
],
[
    'title' => 'Web Developer',
    'company' => 'Innovative Tech Solutions',
    'location' => 'Remote',
    'salary' => '₱28,000.00 / month',
    'type' => 'Remote',
    'posted' => '6 days ago',
    'deadline' => 'Apply before 27 Apr',
    'level' => 'Mid-Senior Level',
    'category' => 'Remote Jobs',
    'logo' => 'web-developer-logo.jpg'
],
[
    'title' => 'Medical Technologist',
    'company' => 'MedTech Innovations',
    'location' => 'Taguig, Philippines',
    'salary' => '₱18,500.00 / month',
    'type' => 'Full time',
    'posted' => '1 day ago',
    'deadline' => 'Apply before 30 Apr',
    'level' => 'Entry Level / Junior',
    'category' => 'All Jobs',
    'logo' => 'medical-technologist-logo.jpg'
],
[
    'title' => 'Nurse Assistant',
    'company' => 'Medicare Services',
    'location' => 'Mandaluyong, Philippines',
    'salary' => '₱16,000.00 / month',
    'type' => 'Full time',
    'posted' => '5 days ago',
    'deadline' => 'Apply before 28 Apr',
    'level' => 'Entry Level / Junior',
    'category' => 'Fresh Grads',
    'logo' => 'nurse-assistant-logo.jpg'
],
[
    'title' => 'HR Manager',
    'company' => 'Global HR Solutions',
    'location' => 'Makati, Philippines',
    'salary' => '₱50,000.00 / month',
    'type' => 'Full time',
    'posted' => '7 days ago',
    'deadline' => 'Apply before 25 Apr',
    'level' => 'Senior Level',
    'category' => 'Hybrid',
    'logo' => 'hr-manager-logo.jpg'
],
[
    'title' => 'Graphic Designer',
    'company' => 'Creative Mind Studios',
    'location' => 'Manila, Philippines',
    'salary' => '₱20,000.00 / month',
    'type' => 'Full time',
    'posted' => '3 days ago',
    'deadline' => 'Apply before 29 Apr',
    'level' => 'Mid-Senior Level',
    'category' => 'New Jobs',
    'logo' => 'graphic-designer-logo.jpg'
],
[
    'title' => 'SEO Specialist',
    'company' => 'RankTech Solutions',
    'location' => 'Cebu City, Philippines',
    'salary' => '₱18,000.00 / month',
    'type' => 'Full time',
    'posted' => '4 days ago',
    'deadline' => 'Apply before 27 Apr',
    'level' => 'Entry Level / Junior',
    'category' => 'Fresh Grads',
    'logo' => 'seo-specialist-logo.jpg'
],
[
    'title' => 'Business Analyst',
    'company' => 'DataSys Innovations',
    'location' => 'Makati, Philippines',
    'salary' => '₱45,000.00 / month',
    'type' => 'Full time',
    'posted' => '6 days ago',
    'deadline' => 'Apply before 28 Apr',
    'level' => 'Mid-Senior Level',
    'category' => 'All Jobs',
    'logo' => 'business-analyst-logo.jpg'
],
[
    'title' => 'Marketing Coordinator',
    'company' => 'Growthify Agency',
    'location' => 'Pasig, Philippines',
    'salary' => '₱22,000.00 / month',
    'type' => 'Full time',
    'posted' => '2 days ago',
    'deadline' => 'Apply before 30 Apr',
    'level' => 'Entry Level / Junior',
    'category' => 'Internship',
    'logo' => 'marketing-coordinator-logo.jpg'
],
[
    'title' => 'Nursing Supervisor',
    'company' => 'Hospicare Solutions',
    'location' => 'Cebu City, Philippines',
    'salary' => '₱35,000.00 / month',
    'type' => 'Full time',
    'posted' => '3 days ago',
    'deadline' => 'Apply before 25 Apr',
    'level' => 'Senior Level',
    'category' => 'Featured Jobs',
    'logo' => 'nursing-supervisor-logo.jpg'
],
[
    'title' => 'Research Scientist',
    'company' => 'BioTech Labs',
    'location' => 'Davao City, Philippines',
    'salary' => '₱42,000.00 / month',
    'type' => 'Full time',
    'posted' => '4 days ago',
    'deadline' => 'Apply before 26 Apr',
    'level' => 'Mid-Senior Level',
    'category' => 'All Jobs',
    'logo' => 'research-scientist-logo.jpg'
],
      
];
?>
